### ISSUE TITLE
Mac Issue : Comparing local vs network (shared) folder

### ISSUE THREAD

**Issue by xterc99** [swisspol/CompareFolders#12]
I don't know how to

Compare a local MacBookAir folder vs network (shared) folder on our family lan

How do you SELECT FOLDER that is on network 

I am a private n

**Comment by swisspol** [comment]
Hi,

You can compare folders on a network drive the same way you can compare folders on a local drive. Just select the left and right folders from the Compare Folders window, and when in the open dialog, navigate to the folders on the network drive.

**Comment by xterc99** [comment]
Thanks for your reply Pierre

Are you sure you can do this from the version off the itunes store for the
Macbook Air ?

Appreciate your response

Thanks and Regards

*Xavier Corray*m :     0408-525151
t   :     03-52439511

**Comment by xterc99** [comment]
Some notes (all under OSX

I tried using a MBA OSX 10.8.5 

When you go to FINDER and NETWORK and pick the remote machine, and try to drill down from a top of tree shared folder by double clicking to display all the child folders/files, CF assumes the double click is ENTER equivalent

Maybe I am just doing the wrong thing ... kindly help

**Comment by swisspol** [comment]
Ah I see. This is not Compare Folders but standard OS X behavior (the Mac is in charge of the open dialog not Compare Folders). Just do a single click and it should browse the folder instead of "selecting" it. If that doesn't work try the buttons at the top of the dialog window to change the view mode: the one in columns should be easier navigate.
